services:
    mysql-db:
        restart: unless-stopped
        container_name: mysql-db
        image: mysql:latest
        ports:
            -3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ...
            MYSQL_USER: ...
            MYSQL_PASSWORD: ...
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
        external: true
